import theme from './appia.json';
import './appia.css';

// export * from 'antd';
export { default as Avatar } from 'antd/es/avatar';
export { default as Button } from 'antd/es/button';
export { default as Tabs } from 'antd/es/tabs';
export { default as Spin } from 'antd/es/spin';
export { default as Alert } from 'antd/es/alert';
export { default as message } from 'antd/es/message';
export { default as List } from 'antd/es/list';
export { default as Skeleton } from 'antd/es/skeleton';
export { default as Modal } from 'antd/es/modal';
export { default as Radio } from 'antd/es/radio';
export { default as Tooltip } from 'antd/es/tooltip';
export { default as Form } from 'antd/es/form';
export { default as Space } from 'antd/es/space';
export { default as Tag } from 'antd/es/tag';
export { default as Select } from 'antd/es/select';
export { default as Checkbox } from 'antd/es/checkbox';
export { default as Empty } from 'antd/es/empty';
export { default as Input } from 'antd/es/input';
export { default as Breadcrumb } from 'antd/es/breadcrumb';
export { default as Popover } from 'antd/es/popover';
export { default as Watermark } from 'antd/es/watermark';
export { default as Badge } from 'antd/es/badge';
export { default as Collapse } from 'antd/es/collapse';
export { default as Image } from 'antd/es/image';
export { default as Progress } from 'antd/es/progress';
export { default as DatePicker } from 'antd/es/date-picker';
export { default as Affix } from 'antd/es/affix';
export { default as Menu } from 'antd/es/menu';
export { default as TimePicker } from 'antd/es/time-picker';
export { default as Switch } from 'antd/es/switch';
export { default as PopConfirm } from 'antd/es/popconfirm';
export { default as InputNumber } from 'antd/es/input-number';
export { default as TextArea } from 'antd/es/input/TextArea';
export { default as AutoComplete } from 'antd/es/auto-complete';
export { default as Upload } from 'antd/es/upload';
export { default as Row } from 'antd/es/row';
export { default as Col } from 'antd/es/col';
export { default as Timeline } from 'antd/es/timeline';

export { theme };
